### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [MiddlePython16/billing_service#4]
Приветствую! 
Вы все отлично постарались. Хорошая дипломная работа. Ниже список замечаний и рекомендаций.

1. [можно лучше] [Этот](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/docker-compose.yaml#L1) параметр с версии 3.7 не является обязательным. Можно его убрать. https://docs.docker.com/compose/
2. [можно лучше] Если добавить ключ --no-cache-dir для [pip](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/Dockerfile#L8), то можно немного уменьшить размер docker-образа. https://pip.pypa.io/en/stable/cli/pip/?highlight=--no-cache#cmdoption-no-cache-dir
3. [можно лучше] [Такой](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/nginx/conf.d/billing.conf#L13) location может посылать много лишних запросов вида  /ddosserver, что в свою очередь может привести к большой нагрузке на сервер django. Используя регулярные выражения, можно сразу отклонять такие запросы и резолвить только /admin и /api:

    ```
    location <регулярное выражение> {
                proxy_pass http://django:8000;
        }
    ```

     Теория про regex-location: https://nginx.org/ru/docs/http/ngx_http_core_module.html#location
     Чтобы потестить конфиг: https://nginx.viraptor.info/

4. [можно лучше] Лучше удалять стандартные джанговские [комментарии](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/src/config/urls.py#L1), так как они не имеют никакого отношения к текущему коду. Это замечание касается всех модулей, где есть джанговский комменты из коробки.
6. [исправить] [Файл](https://github.com/MiddlePython16/billing_service/blob/main/billing_compose/django/src/config/tasks.py) нигде не используется, поэтому лучше его удалить.
7. [можно лучше] [Тут](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/src/extensions/jwt/handlers.py#L11) можно записать короче через тернарный оператор:
    `return header[1] if len(header) else ''`
8. [исправить] [Этот](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/src/extensions/jwt/utils.py#L6) параметр лучше вынести в конфиг, чтобы все настройки содержались в одном месте.
9. [отлично] Молодцы, что не забыли добавить [prefetch_related](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/src/payment/admin.py#L30)!
10. [исправить] [Здесь](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/src/payment/apps.py#L2) не хватает переноса строки.
11. [можно лучше] [Здесь](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/src/payment/receivers.py#L17) наверное лучше сравнивать с объектом PaymentStatus.CONFIRMED из yookassa или вынести этот статус в Enum. Можно случайно ошибиться в написании строкового литерала и потом долго гадать из-за чего произошла ошибка.
12. [исправить] [Импорт](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/src/payment/receivers.py#L5) не используется. Можно его удалить.
13. [исправить] Везде используете одинарные кавычки, а здесь в [f-строке ](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/src/payment/receivers.py#L37)почему-то двойные. [Тут](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/src/payment/providers/yookassa/__init__.py#L114) тоже.
14. Рекомендую заменить числовой [код](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/src/payment/tasks.py#L23) ошибки, на объект [статуса](https://docs.python.org/3/library/http.html#http.HTTPStatus) из библиотеки [http](https://docs.python.org/3/library/http.html). Так будет выглядеть нагляднее и еще мы избавляемся от хардкода.
15. [можно лучше] Чтобы не было лишних [бэкслешей](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/src/payment/tasks.py#L53), можно записать следующим образом:
    ```
    last_payment = (
            payment_model.objects
            .filter(Q(user_id=user), Q(items__in=[item]))
            .prefetch_related('items')
            .order_by('-created')
    ).first()
    ```
16. [исправить] Было бы неплохо собрать все описания [ошибок](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/src/payment/api/v1/serializers/item.py#L32) в одном месте, чтобы в случае чего их можно было оперативно поменять. Может измениться локализация или банально захочется внести правки в текст. Сейчас придется ходить по всему коду, чтобы внести правки, что понятно может отнять прилично времени.
17. [исправить] Видимо [print'ы](https://github.com/MiddlePython16/billing_service/blob/3157aa7177a2c09ac4d188a933614eefdfd263ae/billing_compose/django/src/payment/providers/yookassa/__init__.py#L89) в модуле остались после дебага. Надо заменить логированием.

**Comment by BigDeepBlue** [comment]
Принято!

Удачи на защите диплома :)

**Comment by Wiped-Out** [comment]
Большое спасибо!
